# Syntax highlighting
# highlighter: pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: true

# Setup
title: Dell Donatoni
tagline: My personal website.
email: dell@donatoni.io
description:
#baseurl: "http://donatoni.io"
#baseurl: "http://127.0.0.1:4000"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed

# Build settings
markdown: kramdown

exclude: ['README.md', 'CNAME', 'bower.json', '.gitnore', 'ruby-version', 'bowerrc',]